### ISSUE TITLE
Unable to run it no matter what I try.

### ISSUE THREAD

**Issue by mateuszjarzewski** [libp2p/js-libp2p-webrtc-star#415] opened 2022-03-23 09:11 UTC
I just followed this tutorial:
https://suda.pl/free-webrtc-star-heroku/
The result is error 500
https://thawing-harbor-54478.herokuapp.com/
Same happends when I try to run it in any other way.
Would be nice to be able to run it.

**Comment by mateuszjarzewski** [comment] 2022-03-23 20:17
Would somebody be nice enought to share secret how to run libp2p-websocket-star server? I rly need this ;(

**Comment by achingbrain** [comment] 2022-05-10 16:02
Duplicate of #409

**Closed by achingbrain** 2022-05-10 16:02 UTC
